# Generated by Django 3.2.2 on 2021-05-20 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0006_auto_20210520_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='company',
        ),
    ]
