# Generated by Django 3.2.2 on 2021-05-20 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0009_auto_20210520_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='timeIn',
        ),
        migrations.RemoveField(
            model_name='company',
            name='timeOut',
        ),
    ]
