# Generated by Django 3.2.2 on 2021-06-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0017_auto_20210521_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='camera_url',
            field=models.CharField(default='http://192.168.1.215:8001/stream.mjpg', max_length=200),
            preserve_default=False,
        ),
    ]
