# Generated by Django 3.2.2 on 2021-05-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered', models.IntegerField(default=0)),
                ('exited', models.IntegerField(default=0)),
                ('current_total', models.IntegerField(default=0)),
                ('building_capacity', models.IntegerField(default=0)),
                ('company', models.CharField(max_length=200)),
            ],
        ),
    ]
