# Generated by Django 3.2.2 on 2021-05-20 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movements',
            new_name='Movement',
        ),
    ]
