# Generated by Django 3.2.2 on 2021-05-14 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Counting',
        ),
    ]
