# Generated by Django 3.2.2 on 2021-05-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_rename_choice_counting'),
    ]

    operations = [
        migrations.AddField(
            model_name='counting',
            name='company',
            field=models.CharField(default='Kaws', max_length=200),
            preserve_default=False,
        ),
    ]
