# Generated by Django 3.2.2 on 2021-05-18 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_counting_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counting',
            name='building_capacity',
        ),
    ]
