# Generated by Django 3.2.2 on 2021-05-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_remove_counting_building_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='counting',
            name='building_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
