# Generated by Django 3.2.2 on 2021-05-20 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_auto_20210520_0300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Counting',
            new_name='Company',
        ),
    ]
