# Generated by Django 3.2.2 on 2021-05-18 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_counting_building_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counting',
            name='manager',
        ),
    ]
