# Generated by Django 3.2.2 on 2021-05-19 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_remove_counting_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counting',
            old_name='building_capacity',
            new_name='capacity',
        ),
        migrations.RenameField(
            model_name='counting',
            old_name='current_total',
            new_name='current',
        ),
    ]
