# Generated by Django 3.2.2 on 2021-05-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_rename_counting_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='timeIn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movement',
            name='timeOut',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
