# Generated by Django 3.2.2 on 2021-05-21 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0015_auto_20210521_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='timeIn',
        ),
    ]
